---
- name: Restart facturier compose
  community.docker.docker_compose_v2:
    project_src: "{{ facturier_install_dir }}"
    state: present
    pull: never
    recreate: auto

- name: Restart facturier web only
  community.docker.docker_compose_v2:
    project_src: "{{ facturier_install_dir }}"
    state: present
    services:
      - web
    recreate: auto

- name: Restart facturier api only
  community.docker.docker_compose_v2:
    project_src: "{{ facturier_install_dir }}"
    state: present
    services:
      - api
    recreate: auto
