---
# Inventaire exemple — Production Matrix Stack
# Adapter les IPs à votre infrastructure.

all:
  children:

    matrix_db:
      hosts:
        vm-matrix-db-prod:
          ansible_host: 10.0.1.10  # À remplacer

    matrix_users:
      hosts:
        vm-matrix-users-prod:
          ansible_host: 10.0.1.11  # À remplacer

    matrix_bridges:
      hosts:
        vm-matrix-bridges-prod:
          ansible_host: 10.0.1.12  # À remplacer

    matrix:
      children:
        matrix_db:
        matrix_users:
        matrix_bridges:
