---
proxy_dir: /opt/devops-proxy
caddy_email: "admin@example.com"

promtail_loki_url: "http://10.0.0.16:3100/loki/api/v1/push"
promtail_http_port: 9080
promtail_container_name: promtail
promtail_host_label: "{{ inventory_hostname }}"

sites:
  - name: lavallee
    domain: lavallee.tech
    aliases:
      - www.lavallee.tech
    backend_host: 10.0.0.13
    backend_port: 8080

  - name: wp2-news
    domain: news.lavallee.tech
    aliases: []
    backend_host: 10.0.0.15
    backend_port: 8080

  - name: webcam1-solbach
    domain: webcam.lavallee.tech
    aliases: []
    backend_host: 10.0.0.8
    backend_port: 8080
