deployment_environment: staging

proxy_caddy_email: admin@lavallee.tech

staging_domain_suffix: staging.local

proxy_access_mode: internal_only
proxy_scheme: http

docker_install_compose_plugin: true
