---
ansible_host: 192.168.1.53
ansible_user: devops

facturier_install_dir: /opt/facturier-demo
facturier_web_port: 8080
facturier_api_port: 8000

facturier_app_env: staging
facturier_domain_vitrine: facturier.staging.local
facturier_domain_app: app.facturier.staging.local
facturier_domain_api: api.facturier.staging.local

facturier_enable_api: true
facturier_enable_generation: false

facturier_project_name: facturier-demo
facturier_data_dir: /opt/facturier-demo/data
facturier_scripts_dir: /opt/facturier-demo/scripts
