app_name: invoice
app_env: staging

app_port: 8080
app_domain: invoice.staging.local
app_local_ip: 192.168.1.53

app_install_dir: /opt/invoice-app
docker_project_name: invoice_staging
app_container_name: invoice-app

app_image: nginx
app_image_tag: latest

app_directories:
  - /opt/invoice-app
  - /opt/invoice-app/data
  - /opt/invoice-app/logs

app_ports:
  - "8080:80"

app_volumes: []

app_env_vars: {}

app_healthcheck_enabled: true
app_healthcheck_url: "http://127.0.0.1:8080/"
