---
- name: Import SSH hardening tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Import Fail2ban tasks
  ansible.builtin.import_tasks: fail2ban.yml
  when: hardening_os_fail2ban_enabled

- name: Import firewall tasks  
  ansible.builtin.import_tasks: firewall.yml
  when: hardening_os_firewall_enabled
