---
- name: Deploy API Dockerfile
  ansible.builtin.template:
    src: api.Dockerfile.j2
    dest: "{{ facturier_api_dir }}/Dockerfile"
    owner: "{{ facturier_user }}"
    group: "{{ facturier_group }}"
    mode: "0644"
  notify: Restart facturier api only

- name: Deploy API requirements
  ansible.builtin.template:
    src: requirements.txt.j2
    dest: "{{ facturier_api_dir }}/requirements.txt"
    owner: "{{ facturier_user }}"
    group: "{{ facturier_group }}"
    mode: "0644"
  notify: Restart facturier api only

- name: Deploy API main.py
  ansible.builtin.template:
    src: main.py.j2
    dest: "{{ facturier_api_app_dir }}/main.py"
    owner: "{{ facturier_user }}"
    group: "{{ facturier_group }}"
    mode: "0644"
  notify: Restart facturier api only

- name: Copy generation scripts
  ansible.builtin.copy:
    src: scripts/
    dest: "{{ facturier_scripts_dir }}/"
    owner: "{{ facturier_user }}"
    group: "{{ facturier_group }}"
    mode: preserve
  notify: Restart facturier api only
