---
- name: Run preflight checks
  ansible.builtin.import_tasks: preflight.yml

- name: Create directories
  ansible.builtin.import_tasks: directories.yml

- name: Deploy static web assets
  ansible.builtin.import_tasks: deploy_static.yml

- name: Deploy API files
  ansible.builtin.import_tasks: deploy_api.yml

- name: Deploy compose stack
  ansible.builtin.import_tasks: deploy_compose.yml

- name: Validate deployment
  ansible.builtin.import_tasks: validate.yml
