---
# Inventaire exemple — Staging Matrix Stack
# Adapter les IPs à votre infrastructure.

all:
  children:

    # VM dédiée à PostgreSQL (bases synapse_users + synapse_bridges)
    matrix_db:
      hosts:
        vm-matrix-db-staging:
          ansible_host: 192.168.1.79

    # VM dédiée à Synapse homeserver utilisateurs
    matrix_users:
      hosts:
        vm-matrix-users-staging:
          ansible_host: 192.168.1.78

    # VM dédiée à Synapse homeserver bridges
    matrix_bridges:
      hosts:
        vm-matrix-bridges-staging:
          ansible_host: 192.168.1.77

    # Groupe parent — permet de cibler toutes les VMs Matrix d'un coup
    matrix:
      children:
        matrix_db:
        matrix_users:
        matrix_bridges:
