---
- name: Install central monitoring stack
  ansible.builtin.include_tasks: install_stack.yml
  when: monitoring_observability_install_stack | bool

- name: Validate central monitoring stack
  ansible.builtin.include_tasks: validate.yml
  when: monitoring_observability_install_stack | bool