- name: Create promtail directory
  file:
    path: "{{ promtail_install_dir | default('/opt/promtail') }}"
    state: directory
    mode: "0755"

- name: Deploy promtail compose
  copy:
    src: compose.yml
    dest: "{{ promtail_install_dir | default('/opt/promtail') }}/compose.yml"
    mode: "0644"
  notify: Restart promtail stack

- name: Deploy promtail config
  template:
    src: promtail.yml.j2
    dest: "{{ promtail_install_dir | default('/opt/promtail') }}/promtail.yml"
    mode: "0644"
  notify: Restart promtail stack

- name: Start promtail
  command:
    cmd: docker compose -f compose.yml up -d
    chdir: "{{ promtail_install_dir | default('/opt/promtail') }}"
