[proxies]
vm-proxy ansible_host=192.168.1.48

[monitoring]
vm-monitoring ansible_host=192.168.1.34

[app_hosts]
vm-lavallee-prod ansible_host=192.168.1.33

[production:children]
proxies
monitoring
app_hosts
