---
galaxy_info:
  author: sepp67
  description: Install and manage node_exporter and promtail on Linux hosts
  license: GPL-3.0-only
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
        - all
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - all

dependencies: []