---
all:
  children:

    proxy:
      hosts:
        vm-proxy-staging:
          ansible_host: 192.168.1.56

    apps:
      hosts:
        vm-apps-staging:
          ansible_host: 192.168.1.58

    nextcloud:
      hosts:
        vm-nextcloud-staging:
          ansible_host: 192.168.1.59
