---
- name: Validate and reload caddy
  block:
    - name: Validate Caddy configuration
      ansible.builtin.command:
        chdir: "{{ proxy_dir }}"
        cmd: docker exec caddy caddy validate --config /etc/caddy/Caddyfile
      changed_when: false

    - name: Reload Caddy configuration
      ansible.builtin.command:
        chdir: "{{ proxy_dir }}"
        cmd: docker exec caddy caddy reload --config /etc/caddy/Caddyfile
      changed_when: true
