---
- name: Wait before healthcheck attempts
  ansible.builtin.pause:
    seconds: "{{ app_healthcheck_delay }}"

- name: Check application health endpoint
  ansible.builtin.uri:
    url: "{{ app_healthcheck_url }}"
    method: "{{ app_healthcheck_method }}"
    status_code: "{{ app_healthcheck_status_code }}"
    validate_certs: false
  register: app_healthcheck_result
  retries: "{{ app_healthcheck_retries }}"
  delay: "{{ app_healthcheck_delay }}"
  until: app_healthcheck_result.status == app_healthcheck_status_code
