---
galaxy_info:
  role_name: grav_stack
  author: sepp67
  description: Deploy Grav CMS with persistent volume
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies:
  - role: docker_host
