---
- name: Bootstrap proxy
  import_playbook: proxy-bootstrap.yml

- name: Deploy WordPress backends
  import_playbook: wordpress-backends.yml

- name: Refresh proxy sites
  import_playbook: proxy-sites-refresh.yml