[proxies]
vm-proxy-staging ansible_host=192.168.1.52

[monitoring]
vm-monitoring ansible_host=192.168.1.51

[app_hosts]
vm-facturier-staging ansible_host=192.168.1.22

[staging:children]
proxies
monitoring
app_hosts
