[proxies]
vm-proxy-staging ansible_host=10.0.0.12

[monitoring]
vm-monitoring ansible_host=10.0.0.16

[app_hosts]
vm-facturier-staging ansible_host=10.0.0.25
vm-camera-staging ansible_host=10.0.0.26

[staging:children]
proxies
monitoring
app_hosts
