timezone: Europe/Paris
firewall_enabled: true
ssh_port: 22

# dirs
proxy_dir: /opt/devops-proxy
wp_dir: /opt/devops-wp

caddyfile_path: "{{ proxy_dir }}/Caddyfile"
caddy_email: admin@lavallee.tech

sites:
  - name: lavallee
    domain: lavallee.tech
    backend_host: 10.0.0.13
    backend_port: 8080

  - name: wp2-news
    domain: news.lavallee.tech
    backend_host: 10.0.0.15
    backend_port: 8080

loki_host: "{{ hostvars[groups['monitoring'][0]].ansible_host }}"
loki_url: "http://{{ loki_host }}:3100/loki/api/v1/push"
