---
all:
  children:

    proxy:
      hosts:
        vm-proxy-prod:
          ansible_host: 10.20.1.10

    apps:
      hosts:
        vm-apps-prod:
          ansible_host: 10.20.1.11

    nextcloud:
      hosts:
        vm-nextcloud-prod:
          ansible_host: 10.20.1.12
