---
galaxy_info:
  role_name: nextcloud_stack
  author: sepp67
  description: Deploy Nextcloud stack with PostgreSQL and Redis
  license: MIT
  min_ansible_version: "2.14"
dependencies:
  - role: docker_host
