---
docker_host_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_host_prereq_packages:
  - ca-certificates
  - curl
  - gnupg

docker_host_repo_keyring_dir: /etc/apt/keyrings
docker_host_repo_keyring_ascii_file: /etc/apt/keyrings/docker.asc
docker_host_repo_keyring_file: /etc/apt/keyrings/docker.gpg
docker_host_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
docker_host_repo_arch: "{{ 'amd64' if ansible_architecture in ['x86_64', 'amd64'] else ansible_architecture }}"
docker_host_repo_release: "{{ ansible_lsb.codename | default(ansible_distribution_release) }}"

docker_host_service_enabled: true
docker_host_service_state: started

docker_host_users:
  - "{{ ansible_user | default('devops') }}"