---
docker_compose_version: "2.27.0"
docker_apt_keyring_path: /etc/apt/keyrings/docker.asc
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
