---
galaxy_info:
  role_name: caddy_proxy
  author: sepp67
  description: Deploy Caddy reverse proxy, generate Caddyfile from project registry
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []
